SELECT
  id,
  external_id,
  team_id,
  {{ array_from_string('follower_ids') }} AS follower_ids,
  workflow_id,
  entity_type,
  name,
  abbreviation,
  description,
  app_url,
  stats,
  start_time,
  color,
  iteration_length,
  days_to_thermometer,
  show_thermometer AS is_showing_thermometer,
  archived AS is_archived,
  created_at,
  updated_at,
  loaded_at,
FROM {{ source('shortcut', 'projects') }}
