SELECT
  id,
  global_id,
  external_id,
  name,
  productboard_name,
  {{ array_from_string('owner_ids') }} AS owner_ids,
  {{ array_from_string('follower_ids') }} AS follower_ids,
  milestone_id,
  epic_state_id,
  productboard_plugin_id,
  group_id,
  {{ array_from_string('group_mention_ids') }} AS group_mention_ids,
  productboard_id,
  {{ array_from_string('label_ids') }} AS label_ids,
  mention_ids,
  {{ array_from_string('member_mention_ids') }} AS member_mention_ids,
  {{ array_from_string('project_ids') }} AS project_ids,
  requested_by_id,
  entity_type,
  position,
  stats,
  app_url,
  productboard_url,
  labels,
  stories_without_projects,
  state,
  started_at_override,
  started AS is_started,
  completed AS is_completed,
  archived AS is_archived,
  planned_start_date,
  started_at,
  deadline,
  completed_at,
  completed_at_override,
  created_at,
  updated_at,
  loaded_at,
FROM {{ source('shortcut', 'epics') }}
