SELECT
  id,
  {{ array_from_string('mention_ids') }} AS mention_ids,
  {{ array_from_string('member_mention_ids') }} AS member_mention_ids,
  {{ array_from_string('group_ids') }} AS group_ids,
  {{ array_from_string('group_mention_ids') }} AS group_mention_ids,
  {{ array_from_string('label_ids') }} AS label_ids,
  {{ array_from_string('follower_ids') }} AS follower_ids,
  entity_type,
  name,
  app_url,
  labels,
  stats,
  status,
  start_date,
  end_date,
  created_at,
  updated_at,
  loaded_at,
FROM {{ source('shortcut', 'iterations') }}
