SELECT
  A.id,
  A.loaded_at,
  external_id,
  project_id,
  epic_id,
  requested_by_id,
  {{ array_from_string('owner_ids', remove_quotes=True) }} AS owner_ids,
  {{ array_from_string('follower_ids', remove_quotes=True) }} AS follower_ids,
  {{ array_from_string('mention_ids', remove_quotes=True) }} AS mention_ids,
  {{ array_from_string('group_mention_ids', remove_quotes=True) }} AS group_mention_ids,
  iteration_id,
  workflow_id,
  workflow_state_id,
  story_template_id,
  group_id,
  {{ array_from_string('member_mention_ids', remove_quotes=True) }} AS member_mention_ids,
  {{ array_from_string('label_ids', remove_quotes=True) }} AS label_ids,
  {{ array_from_string('previous_iteration_ids', remove_quotes=True) }} AS previous_iteration_ids,
  entity_type,
  app_url,
  name AS story_name,
  description,
  estimate,
  tasks,
  story_type,
  story_links,
  {{ array_from_string('external_links', remove_quotes=True) }} AS external_links,
  {{ array_from_string('pull_requests', remove_quotes=True) }} AS pull_requests,
  {{ array_from_string('branches', remove_quotes=True) }} AS branches,
  {{ array_from_string('labels', remove_quotes=True) }} AS labels,
  stats,
  {{ array_from_string('comments', remove_quotes=True) }} AS comments,
  {{ array_from_string('commits', remove_quotes=True) }} AS commits,
  {{ array_from_string('files', remove_quotes=True) }} AS files,
  position,
  {{ array_from_string('linked_files', remove_quotes=True) }} AS linked_files,
  {{ array_from_string('custom_fields', remove_quotes=True) }} AS custom_fields,
  custom_fields_arr,
  custom_fields_str,
  lead_time,
  deadline,
  cycle_time,
  started_at_override,
  started_at,
  completed_at,
  completed_at_override,
  moved_at,
  started AS is_started,
  completed AS is_completed,
  archived AS is_archived,
  blocker AS is_blocker,
  blocked AS is_blocked,
  created_at,
  updated_at,
FROM {{ source('shortcut', 'stories') }} AS A
LEFT JOIN (
  SELECT
    id, loaded_at,
    custom_fields AS custom_fields_arr,
    ARRAY_TO_STRING(custom_fields, ',') AS custom_fields_str,
  FROM (
    SELECT
      id, loaded_at,
      ARRAY_AGG(DISTINCT JSON_VALUE(JSON_EXTRACT(arr, '$.value'))) AS custom_fields
    FROM {{ source('shortcut', 'stories') }}
    CROSS JOIN UNNEST(JSON_QUERY_ARRAY(custom_fields)) AS arr
    GROUP BY 1,2
  )
) AS B ON A.id = B.id AND A.loaded_at = B.loaded_at
