SELECT
  id,
  global_id,
  entity_type,
  name,
  description,
  app_url,
  state,
  position,
  stats,
  categories,
  started AS is_started,
  completed AS is_completed,
  archived AS is_archived,
  started_at_override,
  started_at,
  completed_at,
  completed_at_override,
  created_at,
  updated_at,
  loaded_at,
FROM {{ source('shortcut', 'milestones') }}
