SELECT
    ds,
    user_id,
    is_preset,
    active,
    last_login,
    login_count,
    fail_login_count,
    onboarded,
    company_name,
    company_category,
    company_size,
    description,
    created_dttm,
    last_modified_dttm,
    creator_user_id,
    last_modified_user_id,
    email,
    hs_list_id_array,
    email_domain,
    hs_contact_id,
    hs_company_id,
FROM {{ ref('wrk_manager_user') }}
WHERE ds = (SELECT MAX(ds) FROM {{ ref('wrk_manager_user') }})
